### ISSUE TITLE
When will the code be public?

### ISSUE THREAD

**Issue by johnson111788** [tianyu0207/weakly-polyp#1]
Hi,

Thanks for your excellent work! I am really looking forward to your code. May I know when will the code be public?

Best,
Johnson

**Comment by tianyu0207** [comment]
> to

Hi, Thanks for your interest in our work. I have been super busy but I will try to release the code by October.

**Comment by kanydao** [comment]
Hi, 
Thanks for your great job, May I know when will the code be public?

**Comment by tianyu0207** [comment]
> > to
> 
> Hi, Thanks for your interest in our work. I have been super busy but I will try to release the code by October.

Hi yes, I'm currently working on organizing the code and will release it soon.

**Comment by tianyu0207** [comment]
Hi, The code has been released. Thanks for your interests.
