### ISSUE TITLE
about Position embedding in transformer encoder

### ISSUE THREAD

**Issue by Smallwhite999** [tianyu0207/weakly-polyp#2]
Thank you for your great work. I would like to ask if the I3D features extracted by Backbone need to be sent to the transformer encoder. Is the position embedded? If so, how is the position embedded in the 3D data? thank you!
![图片](https://user-images.githubusercontent.com/56509992/192724775-b0d68698-b947-4542-bbf3-303077471b30.png)

**Comment by tianyu0207** [comment]
> Thank you for your great work. I would like to ask if the I3D features extracted by Backbone need to be sent to the transformer encoder. Is the position embedded? If so, how is the position embedded in the 3D data? thank you! ![图片](https://user-images.githubusercontent.com/56509992/192724775-b0d68698-b947-4542-bbf3-303077471b30.png)

Hi Thanks for your interest. The code has been released.
